version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.6-node
    steps:
      - checkout
      - ruby/install-deps
      # Store bundle cache
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
  test:
    parallelism: 3
    docker:
      - image: cimg/ruby:2.6.6-node
      - image: circleci/postgres:9.5-alpine
        environment:
          POSTGRES_USER: windaily_boss
          POSTGRES_DB: windaily_test
          POSTGRES_PASSWORD: postgres_password_for_win_daily
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: windaily_boss
      PGPASSWORD: postgres_password_for_win_daily
      RAILS_ENV: windaily_test
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: "yarn.lock"
      - run:
          name: Wait for DB
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: Create database setup
          command: bundle exec bin/setup
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: Run Rails Test
          command: bundle exec rails test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
            - rails test
