version: 2.1

orbs:
  ruby: circleci/ruby@1.1.0
  node: circleci/node@2

jobs:
  build:
    steps:
      - run:
          name: Create database setup
          command: bundle exec bin/setup
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
  test:
    parallelism: 3
    environment:
      BUNDLE_JOBS: "3"
      BUNDLE_RETRY: "3"
      PGHOST: 127.0.0.1
      PGUSER: windaily_boss
      PGPASSWORD: postgres_password_for_win_daily
      RAILS_ENV: windaily_test
    steps:
      - rails test:
          name: Run rails testing framework
          command: bundle exec rails test


workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - rails test
