default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: windaily

test:
  <<: *default
  database: windaily_test

production:
  <<: *default
  database: windaily_production
  username: windaily_boss
  password: <%= ENV['WINDAILY_DATABASE_PASSWORD']
